server:
  port: 8083

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Start2024
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296






# Logging Configuration
#logging:
 # level:
  #  org:
   #   springframework: DEBUG
    #  hibernate: DEBUG

      # Server Port (default is 8080, uncomment to change)
      # server:
      #   port: 8080




